### ISSUE TITLE
Dialog size information isn't communicated properly to MPR

### ISSUE THREAD

**Issue by Ansku** [vaadin/vaadin-dialog-flow#209]
In 14.2 branch V8 contents within a Dialog have their layouting triggered before Dialog gains its actual size, and the layouting isn't retriggered once that has happened. Likewise it's not triggered if the Dialog's size is changed either manually or programmatically. For elements that have programmatically calculated fixed sizes, such as TabSheet contents, this leads to too small final sizes.

Test project that reproduces the issue can be found attached in https://vaadin.com/pro/support#3435 (accessible by Vaadin staff only)
Tested on 14.2.1 and 14.2.3.

Workarounds:
1. Give Dialog contents fixed size so that the elements deeper within the layout don't have to measure themselves based on Dialog's size.
2. `dialog.getElement().executeJs("vaadin.forceLayout()");` whenever initializing or resizing happens -- only works out-of-the-box if MPR has already been initialized when the Dialog is opened/resized, otherwise it may be necessary to add an attach listener to the legacy contents and a delay to the call, such as `dialog.getElement().executeJs("setTimeout(function(){ vaadin.forceLayout() }, 300)");`

**Comment by tomivirkki** [comment]
To me this kind of sounds like a chicken and egg problem. The Dialog doesn't have a defined size so it is, by default, sized by its content. But in this case the content doesn't have a size either, but takes 100% (`dl.setSizeFull();`, `ts.setSizeFull();`) of the dialog's size (which hasn't been set) so you end up with a size that's unpredictable.

This is probably something that should be fixed in the app, instead of the component. For example, if you want your Dialog to always have full size:
`d.setSizeFull()`
That will enable relative size for the content also (`dl.setSizeFull` if you will):

![dialog-setsizefull](https://user-images.githubusercontent.com/1222264/89912710-8a319180-dbfb-11ea-9189-c808ad4edf3e.gif)

...or, if you want your layout to always have some specific width:
`dl.setWidth("500px")`
Now the Dialog would adjust to the width of the content:

![dialog-content-width](https://user-images.githubusercontent.com/1222264/89913578-8d794d00-dbfc-11ea-9a1f-3eae16200165.gif)

V14 did have the same issue, but it just manifested differently. I wouldn't call that behavior expected/deterministic either:

![mpr-sizing-v14-1](https://user-images.githubusercontent.com/1222264/89912556-5c4c4d00-dbfb-11ea-9ce5-3b8ca4816a63.gif)

**Comment by Ansku** [comment]
I think you got turned around somewhere, the Dialog in the test application does have its size set with `setHeight("95vh");` and the problem is still present. MPR doesn't get notified when the Dialog actually grows to that size.

**Comment by Ansku** [comment]
...and if you add ` d.setWidth("300px");` to give it a fixed initial width (that is narrower than the full text) as well, it's still broken if you then call `d.setWidth("95vw");` from the Resize button. Sorry, should have said that in the initial comment as well, but those gifs flashing make me nauseous...

**Comment by tomivirkki** [comment]
> the Dialog in the test application does have its size set with setHeight("95vh");

The test app has the Dialog's _height_ defined but with "size" I was referring to both axis (width and height); setSizeFull vs setHeight/setWidth....sorry for the confusion

> MPR doesn't get notified when the Dialog actually grows to that size

As you can see in the very last gif, if Vaadin 8 gets notified of the size change, the dialog with this setup gets a different width every time, so I don't think the size change notification alone helps here.

> ...and if you add d.setWidth("300px"); to give it a fixed initial width (that is narrower than the full text) as well, it's still broken if you then call d.setWidth("95vw"); 

This issue isn't specific to Dialog. You get wrongly sized TabSheet internals even if you place the MPR view inside a small Div and dynamically expand it:

![Screenshot 2020-08-12 at 8 35 21](https://user-images.githubusercontent.com/1222264/89979712-1209b100-dc79-11ea-87fe-5276f91c31f5.png)

I'm not that familiar with MPR but it seems that using relative sizes for MPR views is problematic. Using fixed size does fix the issue but it is...well....fixed size:

```java
lw.setWidth("500px");
lw.setHeight("400px");
```

**Comment by Ansku** [comment]
> This issue isn't specific to Dialog. You get wrongly sized TabSheet internals even if you place the MPR view inside a small Div and dynamically expand it
I'm not that familiar with MPR but it seems that using relative sizes for MPR views is problematic.

Somehow managed to miss this reply until now, but if that's the case we have even a bigger issue at hand and should do something about it ASAP.  No proper support for relative sizes is very much not ideal... The legacy component wrappers should definitely have an element resize listener that communicates changes to LayoutManager.

This test application doesn't work quite properly even with fixed Dialog size and not resizing, though. If you close the first Dialog and reopen it, the first tab is empty until you toggle to the other tab and back, even if it's a completely new Dialog and new TabSheet instance upon reopening so 'should' be initialized just the same on every opening. The same workaround with forceLayout gets around that as well.

**Comment by tomivirkki** [comment]
I think the following fixes should do it:
- `LegacyWrapper` client should use `@polymer/iron-resizable-behavior` (which is what V10+ uses for size change notifications) and on size change, as you said, communicate the change to LayoutManager. Can u make a separate issue for this?
- `vaadin-overlay` should make sure to notify iron-resizable-behavior whenever it's opened. [Dialog already does this but only on resize](https://github.com/vaadin/vaadin-dialog/blob/master/src/vaadin-dialog-resizable-mixin.html#L213).
